const products = [
    { key: "applelaptop", name: "Apple Laptop", price: 124999, model: "applelaptop.glb" },
    { key: "asuslaptop", name: "Asus Laptop", price: 68999, model: "asus laptop.glb" },
    { key: "coolerglass1", name: "Cooler Glass 1", price: 799, model: "coolerglass1.glb" },
    { key: "Glasses_silver_Glasses_silver_0", name: "Cooler Glass 2", price: 799, model: "Glasses_silver_Glasses_silver_0.glb" },
    { key: "coolerglass3", name: "Cooler Glass 3", price: 799, model: "coolerglass3.glb" },
    { key: "coolerglass4", name: "Cooler Glass 4", price: 799, model: "coolerglass4.glb" },
    { key: "Glasses_silver_Glasses_silver_0001", name: "Cooler Glass 5", price: 799, model: "Glasses_silver_Glasses_silver_0001.glb" },
    { key: "coolerglass6", name: "Cooler Glass 6", price: 799, model: "coolerglass6.glb" },
    { key: "coolerglass7", name: "Cooler Glass 7", price: 799, model: "coolerglass7.glb" },
    { key: "coolerglass8", name: "Cooler Glass 8", price: 799, model: "coolerglass8.glb" },
    { key: "headset1", name: "Headset 1", price: 2499, model: "headset1.glb" },
    { key: "Object_17002", name: "Headset 2", price: 2699, model: "Object_17002.glb" },
    { key: "lambert1", name: "Heel Sandal 1", price: 1599, model: "lambert1.glb" },
    { key: "heel2", name: "Heel Sandal 2", price: 1699, model: "heel2.glb" },
    { key: "heel3", name: "Heel Sandal 3", price: 1499, model: "heel3.glb" },
    { key: "heel4", name: "Heel Sandal 4", price: 1399, model: "heel4.glb" },
    { key: "hp_laptop001", name: "HP Laptop", price: 59999, model: "hp_laptop001.glb" },
    { key: "lenovolaptop", name: "Lenovo Laptop", price: 54999, model: "lenovolaptop.glb" },
    { key: "mobile1", name: "Mobile 1", price: 22999, model: "mobile1.glb" },
    { key: "Object_4002", name: "Mobile 2", price: 24999, model: "Object_4002.glb" },
    { key: "Object_2004", name: "Mobile 3", price: 19999, model: "Object_2004.glb" },
    { key: "Object_2005", name: "Sneaker 1", price: 1999, model: "Object_2005.glb" },
    { key: "nike", name: "Sneaker 2", price: 2199, model: "nike.glb" },
    { key: "shoe3", name: "Sneaker 3", price: 1899, model: "shoe3.glb" },
    { key: "Winter_shoe_size32_low_sculpted_Winter_shoe_size32_low_sculpted", name: "Sneaker 4", price: 2099, model: "Winter_shoe_size32_low_sculpted_Winter_shoe_size32_low_sculpted.glb" },
    { key: "shoe5", name: "Sneaker 5", price: 1799, model: "shoe5.glb" },
    { key: "shoe61", name: "Sneaker 6", price: 1999, model: "shoe61.glb" },
    { key: "Object_3002", name: "Sneaker 9", price: 1899, model: "Object_3002.glb" },
    { key: "shoe10", name: "Sneaker 10", price: 1699, model: "shoe10.glb" },
    { key: "defaultMaterial", name: "Sneaker 11", price: 1599, model: "defaultMaterial.glb" },
    { key: "shoe12", name: "Sneaker 12", price: 1499, model: "shoe12.glb" },
    { key: "SM_Speaker_01_Speaker_01_0", name: "Bluetooth Speaker", price: 2999, model: "SM_Speaker_01_Speaker_01_0.glb" },
    { key: "Object_104", name: "Toy 1", price: 499, model: "Object_104.glb" },
    { key: "toy2", name: "Toy 2", price: 499, model: "toy2.glb" },
    { key: "Cube_Material_0", name: "Toy 3", price: 499, model: "Cube_Material_0.glb" },
    { key: "Object_2014", name: "Toy 4", price: 499, model: "Object_2014.glb" },
    { key: "Circle008_Tank_0", name: "Toy 5", price: 499, model: "Circle008_Tank_0.glb" },
    { key: "toy6", name: "Toy 6", price: 499, model: "toy6.glb" },
    { key: "toy7", name: "Toy 7", price: 499, model: "toy7.glb" },
    { key: "toy8", name: "Toy 8", price: 499, model: "toy8.glb" },
    { key: "Material1", name: "Toy 9", price: 499, model: "Material1.glb" },
    { key: "Object_3004", name: "Toy 10", price: 499, model: "Object_3004.glb" },
    { key: "toy11", name: "Toy 11", price: 499, model: "toy11.glb" },
    { key: "toy12", name: "Toy 12", price: 499, model: "toy12.glb" },
    { key: "toy13", name: "Toy 13", price: 499, model: "toy13.glb" },
    { key: "waterfish_low_lambert1_0", name: "Toy 14", price: 499, model: "waterfish_low_lambert1_0.glb" },
    { key: "toy15", name: "Toy 15", price: 499, model: "toy15.glb" },
    { key: "tv", name: "Smart TV", price: 39999, model: "tv.glb" },
    { key: "watch1", name: "Watch 1", price: 2999, model: "watch1.glb" },
    { key: "Object_8", name: "Watch 2", price: 3199, model: "Object_8.glb" },
    { key: "watch3", name: "Watch 3", price: 3499, model: "watch3.glb" },
    { key: "watch4", name: "Watch 4", price: 3799, model: "watch4.glb" },
    { key: "Watches_Chopard2_Watches_Chopard_1K_0", name: "Watch 5", price: 2899, model: "Watches_Chopard2_Watches_Chopard_1K_0.glb" },
    { key: "watch6", name: "Watch 6", price: 2599, model: "watch6.glb" },
    { key: "watch7", name: "Watch 7", price: 2799, model: "watch7.glb" },
    { key: "watch8", name: "Watch 8", price: 2999, model: "watch8.glb" }
  ];
  
  module.exports = products;